AllCops:
  TargetRubyVersion: 3.0.3
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'bin/**'
    - 'db/schema.rb'
    - 'vendor/**/*'

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context']

Metrics/AbcSize:
  Exclude:
    - 'app/lib/user_authenticator.rb'

Metrics/MethodLength:
  Exclude:
    - 'app/lib/user_authenticator.rb'
    -